trigger: none

pr: none

parameters:
  - name: releaseDescription
    displayName: 'Release description'
    type: string
    default: ''
  - name: runAutomatedTest
    displayName: 'Run automated tests'
    type: boolean
    default: true
  - name: createPullRequest
    displayName: 'Create pull request automatically'
    type: boolean
    default: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  BOT_NAME: $(BOT-NAME)
  COGNIGY_BASE_URL_DEV: $(COGNIGY_BASE_URL_DEV)
  COGNIGY_BASE_URL_TEST: $(COGNIGY_BASE_URL_TEST)
  COGNIGY_BASE_URL_PROD: $(COGNIGY_BASE_URL_PROD)
  COGNIGY_API_KEY_DEV: $(COGNIGY_API_KEY_DEV)
  COGNIGY_API_KEY_TEST: $(COGNIGY_API_KEY_TEST)
  COGNIGY_API_KEY_PROD: $(COGNIGY_API_KEY_PROD)
  MAX_SNAPSHOTS: $(MAX_SNAPSHOTS)
  PYTHONUNBUFFERED: 1

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  - script: |
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      python helper_files/extract_agent.py
    displayName: 'Run Extraction Script'
    env:
      RUN_AUTOMATED_TEST: ${{ parameters.runAutomatedTest }}
      BOT_NAME: $(BOT_NAME)
      COGNIGY_BASE_URL_DEV: $(COGNIGY_BASE_URL_DEV)
      COGNIGY_BASE_URL_TEST: $(COGNIGY_BASE_URL_TEST)
      COGNIGY_BASE_URL_PROD: $(COGNIGY_BASE_URL_PROD)
      COGNIGY_API_KEY_DEV: $(COGNIGY_API_KEY_DEV)
      COGNIGY_API_KEY_TEST: $(COGNIGY_API_KEY_TEST)
      COGNIGY_API_KEY_PROD: $(COGNIGY_API_KEY_PROD)
      MAX_SNAPSHOTS: $(MAX_SNAPSHOTS)
      RELEASE_DESCRIPTION: ${{ parameters.releaseDescription }}
      PYTHONUNBUFFERED: 1

  - script: |
      sudo apt-get install gh
    displayName: 'Install GitHub CLI'

  - script: |
      PR_BODY=$(cat .github/pull_request_template.md)
      PR_BODY=$(echo "$PR_BODY" | sed "s/PLACEHOLDER_RUN_AUTOMATED_TEST/${{ parameters.runAutomatedTest }}/g")
      PR_BODY=$(echo "$PR_BODY" | sed "s/PLACEHOLDER_RELEASE_DESCRIPTION/${{ parameters.releaseDescription }}/g")
      gh pr create \
        --title "Pull Request on $(git rev-parse --abbrev-ref HEAD)" \
        --body "$PR_BODY" \
        --base main \
        --head "$(git rev-parse --abbrev-ref HEAD)" \
        --label "automated-test"
    displayName: 'Create Pull Request'
    condition: eq('${{ parameters.createPullRequest }}', 'true')
    env:
      GH_TOKEN: $(GH_TOKEN)