name: Deploy Agent

on:
  push:
    branches:
      - main
    paths:
      - agent/snapshot/**

jobs:
  post-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Add your post-merge steps below
      - name: Example Step
        run: |
          echo "This workflow runs after a merge into main."
      - name: Check last commit author for snapshot file
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an' agent/snapshot/*)
          if [ "$AUTHOR" != "github-actions[bot]" ]; then
            echo "Snapshot file was manually changed by $AUTHOR. Failing pipeline."
            exit 1
          fi